# Basic
title: Li Shiwang
subtitle: 个人站
description: Just go for it!
creator: <a href="http://jggnice.top">@jggnice</a>

url: "http://jggnice.top"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
# markdown: redcarpet
# redcarpet:
  # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客

# Navigation buttons in the front page.s
nav:
    - {title: TestPage, description: TestPage, url: 'http://jggnice.top/hexo-test'}
    
# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: leopard
    duoshuo: leopard 

# Social
social:
    weibo: 3847637730 
    github: jggnice 
    tencentweibo: whysocute 
    qq: 1362884249 
    topit: 3410007 
    lofter: t69252677 
    mail: whysocute@qq.com 
    # twitter: 

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
